"""Published API contracts; source revisions are recorded in tests/parity-audit.json."""

TASK_PATH = "/midjourney/tasks"

ENDPOINTS = {
    "midjourney_imagine": {
        "method": "POST",
        "path": "/midjourney/imagine",
        "operation": "generate",
        "schema": {
            "type": "object",
            "properties": {
                "mask": {"type": "string"},
                "mode": {"enum": ["fast", "relax", "turbo"], "type": "string"},
                "action": {"type": "string"},
                "prompt": {"type": "string"},
                "timeout": {"type": "number"},
                "image_id": {"type": "string"},
                "translation": {"type": "boolean"},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
                "split_images": {"type": "boolean"},
                "version": {"type": "string", "enum": ["8.2", "8.1", "8", "7", "6.1", "6", "5.2"]},
                "hd": {"type": "boolean"},
                "quality": {"type": "string"},
                "style_reference": {"type": "boolean"},
                "moodboard": {"type": "boolean"},
            },
        },
        "properties": {
            "mask": {"type": "string"},
            "mode": {"enum": ["fast", "relax", "turbo"], "type": "string"},
            "action": {"type": "string"},
            "prompt": {"type": "string"},
            "timeout": {"type": "number"},
            "image_id": {"type": "string"},
            "translation": {"type": "boolean"},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
            "split_images": {"type": "boolean"},
            "version": {"type": "string", "enum": ["8.2", "8.1", "8", "7", "6.1", "6", "5.2"]},
            "hd": {"type": "boolean"},
            "quality": {"type": "string"},
            "style_reference": {"type": "boolean"},
            "moodboard": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {"action": "generate", "version": "8.2", "mode": "fast"},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "midjourney_edits": {
        "method": "POST",
        "path": "/midjourney/edits",
        "operation": "edit",
        "schema": {
            "type": "object",
            "properties": {
                "mask": {"type": "string"},
                "mode": {"enum": ["fast", "relax", "turbo"], "type": "string"},
                "action": {"type": "string"},
                "prompt": {"type": "string"},
                "image_url": {"type": "string"},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
                "split_images": {"type": "boolean"},
            },
        },
        "properties": {
            "mask": {"type": "string"},
            "mode": {"enum": ["fast", "relax", "turbo"], "type": "string"},
            "action": {"type": "string"},
            "prompt": {"type": "string"},
            "image_url": {"type": "string"},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
            "split_images": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {"action": "generate", "mode": "fast"},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "midjourney_describe": {
        "method": "POST",
        "path": "/midjourney/describe",
        "operation": "describe",
        "schema": {
            "type": "object",
            "required": ["image_url"],
            "properties": {"image_url": {"type": "string"}},
        },
        "properties": {"image_url": {"type": "string"}},
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "midjourney_translate": {
        "method": "POST",
        "path": "/midjourney/translate",
        "operation": "translate",
        "schema": {
            "type": "object",
            "required": ["content"],
            "properties": {"content": {"type": "string"}},
        },
        "properties": {"content": {"type": "string"}},
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "midjourney_videos": {
        "method": "POST",
        "path": "/midjourney/videos",
        "operation": "video",
        "schema": {
            "type": "object",
            "properties": {
                "action": {"enum": ["generate", "extend"], "type": "string"},
                "mode": {"enum": ["fast", "turbo"], "type": "string"},
                "resolution": {"enum": ["480p", "720p"], "type": "string"},
                "prompt": {"type": "string"},
                "video_id": {"type": "string"},
                "video_index": {"type": "number"},
                "loop": {"type": "boolean"},
                "image_url": {"type": "string"},
                "end_image_url": {"type": "string"},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "action": {"enum": ["generate", "extend"], "type": "string"},
            "mode": {"enum": ["fast", "turbo"], "type": "string"},
            "resolution": {"enum": ["480p", "720p"], "type": "string"},
            "prompt": {"type": "string"},
            "video_id": {"type": "string"},
            "video_index": {"type": "number"},
            "loop": {"type": "boolean"},
            "image_url": {"type": "string"},
            "end_image_url": {"type": "string"},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {"action": "generate", "mode": "fast"},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "midjourney_get_seed": {
        "method": "POST",
        "path": "/midjourney/seed",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["image_id"],
            "properties": {"image_id": {"type": "string"}},
        },
        "properties": {"image_id": {"type": "string"}},
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "midjourney_shorten": {
        "method": "POST",
        "path": "/midjourney/shorten",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["prompt"],
            "properties": {"prompt": {"type": "string"}},
        },
        "properties": {"prompt": {"type": "string"}},
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "midjourney_task_retrieve": {
        "method": "POST",
        "path": "/midjourney/tasks",
        "operation": "task",
        "schema": {
            "type": "object",
            "properties": {
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
                "id": {"type": "string"},
                "trace_id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}},
                "trace_ids": {"type": "array", "items": {"type": "string"}},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
            },
        },
        "properties": {
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            "id": {"type": "string"},
            "trace_id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}},
            "trace_ids": {"type": "array", "items": {"type": "string"}},
            "offset": {"type": "integer"},
            "limit": {"type": "integer"},
        },
        "parameters": [],
        "defaults": {"wait_seconds": 0},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
    "midjourney_tasks_retrieve_batch": {
        "method": "POST",
        "path": "/midjourney/tasks",
        "operation": "batch",
        "schema": {
            "type": "object",
            "properties": {
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
                "id": {"type": "string"},
                "trace_id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
                "trace_ids": {"type": "array", "items": {"type": "string"}},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
            },
            "required": ["action"],
        },
        "properties": {
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            "id": {"type": "string"},
            "trace_id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
            "trace_ids": {"type": "array", "items": {"type": "string"}},
            "offset": {"type": "integer"},
            "limit": {"type": "integer"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {"action": "retrieve_batch"},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
}
